### ISSUE TITLE
Issues with the scale on fast SSDs

### ISSUE THREAD

**Issue by zsaleeba** [stolk/diskgraph#1]
Nice program! I had a problem running it on my Corsair Force MP600 SSD which runs PCIe 4 and theoretically supports a peak of around 5TB per second transfer rates.
This is what I see when suspending a large VM in virtualbox:
![image](https://user-images.githubusercontent.com/192930/117904727-392f0500-b315-11eb-8e0a-9aef512f6ded.png)
Note the vertical scale is a bit messed up.

**Comment by stolk** [comment]
Ha! I just hit the same bug on my WD Black NVMe. And fixed it. Thanks for trying it out, and reporting! The current version should work on fast disks now.

I think it is triggered when the vertical scale goes to 4GBit/s or higher.

**Comment by zsaleeba** [comment]
Thanks. It works great now.
