### ISSUE TITLE
diskgraph uses a ton of bandwidth over SSH

### ISSUE THREAD

**Issue by scottchiefbaker** [stolk/diskgraph#7]
Seems like a good application for this utility would be to SSH in to a server and run `diskgraph` while generating load. When I run `diskgraph` remotely on my server I'm seeing about 10Mb/s of traffic. That seems **crazy high** for a text based application. I'm not sure why it would need that much bandwidth, but it's something worth looking in to.

**Comment by stolk** [comment]
Ah, sorry, yes... it redraws the plot every frame. So it is not very efficient with network use. I will mention it in the README as a known issue.

**Comment by stolk** [comment]
By design. This can be mitigated by resizing to a smaller terminal.
For 80x24 terminal, I have measured with pv the bandwidth to be 263KiB/s.
